version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo:4.0.10
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: jobOffersDataBase
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always  #restart the container regardless of the exit status
    ports:
      - "8081:8081"  # port forwarding
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_URL: mongodb://root:toor@mongo:27017/  # mongodb://{mongo-image-username}:{mongo-image-password}@{mongo-image-name}:{port}

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "63792:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8082:8081"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379

  job-offers:
    container_name: job-offers
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_USER: jobOffersUser
      MONGO_PASSWORD: jobOffersPassword
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: jobOffersDataBase
      MONGO_AUTH_SOURCE: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
