offer-url.host=http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
offer-url.port=5057
spring.data.mongodb.uri=mongodb://jobOffersUser:jobOffersPassword@localhost:27017/jobOffersDataBase
mongock.change-logs-scan-package: pl.offers.job
